### ISSUE TITLE
BUG: Breaking change introduced in latest version of tfsec

### ISSUE THREAD

**Issue by Hobdell** [aquasecurity/tfsec-sarif-action#16]
The latest version (v1.0.0) of tfsec released on 28/01/2022: https://github.com/aquasecurity/tfsec/releases/ has introduced a number of breaking changes. Including the behaviour of --out and --format arguments. 

This is causing a failure when using tfsec-sarif-action, particularly at this command:
```

 tfsec --format=sarif ./my_project
panic: value is unknown

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0xd12ef8, 0xc0000a9ae1}}, {0xadb7c0, 0x12e7740}})
	/home/runner/work/tfsec/tfsec/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1262 +0x111
github.com/aquasecurity/tfsec/internal/pkg/block.getStrings({0xd12ad0, 0xc000413c20}, 0xc000413c20)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/attribute.go:256 +0x28b
github.com/aquasecurity/tfsec/internal/pkg/block.getStrings({0xd12c58, 0xc0006150e0}, 0x9)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/attribute.go:251 +0x5f2
github.com/aquasecurity/tfsec/internal/pkg/block.(*Attribute).ValueAsStrings(...)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/attribute.go:243
github.com/aquasecurity/tfsec/internal/pkg/adapter/aws/iam.parseStatement(0xc000e0af50)
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/aws/iam/convert.go:119 +0x207
github.com/aquasecurity/tfsec/internal/pkg/adapter/aws/iam.ConvertTerraformDocument({0xc000e32d00, 0x19, 0x20}, 0xc000798460)
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/aws/iam/convert.go:73 +0x270
github.com/aquasecurity/tfsec/internal/pkg/adapter/aws/iam.findAllPolicies({0xc000e32d00, 0x19, 0x20}, 0xc00048b360, 0xc000e0b5a8)
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/aws/iam/convert.go:195 +0x5f1
github.com/aquasecurity/tfsec/internal/pkg/adapter/aws/iam.parsePolicyFromAttr(0xc000590c30, 0xc00048b360, {0xc000e32d00, 0xc000e0b648, 0x1})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/aws/iam/convert.go:20 +0x58
github.com/aquasecurity/tfsec/internal/pkg/adapter/aws/iam.adaptPolicies({0xc000e32d00, 0x19, 0x20})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/aws/iam/policies.go:44 +0x15e
github.com/aquasecurity/tfsec/internal/pkg/adapter/aws/iam.Adapt({_, _, _})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/aws/iam/adapt.go:11 +0xb3
github.com/aquasecurity/tfsec/internal/pkg/adapter/aws.Adapt({_, _, _})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/aws/adapt.go:63 +0x865
github.com/aquasecurity/tfsec/internal/pkg/adapter.Adapt({0xc000e32d00, 0x19, 0x20})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/adapt.go:19 +0x4e
github.com/aquasecurity/tfsec/internal/pkg/scanner.(*Scanner).Scan(0xc0009a33e0, {0xc000e32d00, 0x0, 0x20})
	/home/runner/work/tfsec/tfsec/internal/pkg/scanner/scanner.go:51 +0x9f
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.glob..func1(0x127c060, {0xc0001d5fc0, 0x1, 0x2})
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:114 +0x7ec
github.com/spf13/cobra.(*Command).execute(0x127c060, {0xc00008c160, 0x2, 0x2})
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x127c060)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:11 +0x25
+ tfsec_return=2
+ exit_code=2
+ echo ::set-output name=tfsec-return-code::2
```

**Comment by owenrumney** [comment]
this should have been fixed in later versions - there was a disconnect in the version of go-cty we use and the one that HashiCorp use.

We've locked ourselves in step with theirs now
