### ISSUE TITLE
rejecting SARIF, as there are more results per run than allowed

### ISSUE THREAD

**Issue by xomgc3** [aquasecurity/tfsec-sarif-action#43]
Generally, `tfsec` is a great tool.  We have a couple of very large directories in one of our repos that are throwing this error when attempting to upload the results to GHAS.

```
Error: Code Scanning could not process the submitted SARIF file:
rejecting SARIF, as there are more results per run than allowed (42118 > 25000)
Error: Code Scanning could not process the submitted SARIF file:
rejecting SARIF, as there are more results per run than allowed (42118 > 25000)
    at Object.waitForProcessing (/runner/_work/_actions/github/codeql-action/v2/lib/upload-lib.js:329:23)
    at async run (/runner/_work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:55:13)
    at async runWrapper (/runner/_work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:70:9)
```

How should the "more results per run than allowed" be resolved?  Thanks!

**Comment by xomgc3** [comment]
Could [this](https://github.com/github/codeql/issues/12717) be related?
